---
title: "Lab6"
author: "Soyeon Lee"
date: "10/21/2020"
output: html_document
---
1. Write a function that conducts a randomization test for the mean difference between two groups, and show that it works. Specifically, using your function, conduct a randomization test on the same data we used in the above example from lab. Report the results and briefly discuss what the results of the randomization tell you. (6 points). Extra: if the observed mean difference in the experiment was found to be .5, what would you have concluded from the randomization test?
Inputs:

the inputs should include a vector for group 1, and vector for group 2, and the number of permutations/re-samplings of the data to create.
Outputs:

output each group mean, and the difference between group means
output a histogram of the sampling distribution of the possible mean differences produced by the randomization process
output the probability or odds of obtaining the observed mean difference or larger.
Confidence=20
```{r}
the_data<-read.csv("open_data/SchroederEpley2015data.csv", header=TRUE)

library(dplyr)
colnames(the_data)[colnames(the_data)=='CONDITION']<-'condition'


randomization_test<-function(a,b, resample=100){
#calculate actual means  
  A_mean<-mean(a)
  B_mean<-mean(b)
  mean_difference<-A_mean-B_mean

#shuffle for random sampling
  all_values<-c(a,b)
  
  sample_differences <- c()
  for(i in 1:resample){
    resample <- sample(all_values)
    new_A_mean <- mean(resample[1:length(a)])
    new_B_mean <- mean(resample[(length(a)+1):length(all_values)])
    sample_differences[i] <- new_A_mean-new_B_mean
  }

  test_output<-list(group_A_mean=A_mean,
                    group_B_mean=B_mean,
                    AB_difference=mean_difference,
                    random_samples=sample_differences)
  
  return(test_output)
}

#plot
qplot(mean_differences)+
  geom_histogram(color="orange")+
  geom_vline(xintercept=2, color ="red")+
  theme_classic()

group_1<-c(1,2,3,4,7)
group_2<-c(6,7,3,9,8)
```

